### ISSUE TITLE
Need help with this project?

### ISSUE THREAD

**Issue by bufke** [gethuman/nativescript-sidedrawer#22]
Hello, there isn't much activity on this project these days. I'd like to fix some bugs I face with it, the biggest issue is that hitting the back button to exit the application in android and re-entering causes the side drawer to no longer be built - but nativescript-sidedrawer will still refuse to build it a second time even though the initial build no longer exists.

I wasn't able to run this repo at all to get the demo - I suspect because of out of date packages. I was able to use the nativescript-plugin-seed project to copy sidedrawer into and get it running that way. However that completely restructures the repo making it impossible for me to really make a pull request.

I think I'll need to proceed in one of the following ways

- You'll need to help me modernize this project so that it's possible to git clone and run the demo.
- I can simply make my own project based on this
- We can rebase the project from nativescript-plugin-seed and merge the results in here - including restructuring the layout

This project is useful to me because it's GPL compatible unlike Nativescript UI's sidedrawer. Unfortunately one thing I can't do is test anything on iOS - but it should work as the seed project supports it.

**Comment by roblav96** [comment]
@bufke Feel free to fork and do whatever, but everyones adopted to the official sidedrawer.

**Comment by bufke** [comment]
Ok my work is [here](https://gitlab.com/burke-software/nativescript-sidedrawer) if anyone is interested. 

My understanding is that UI cannot be used with GPL code. See [this issue](https://github.com/telerik/nativescript-ui-feedback/issues/114). So the main audience would be those who prefer or need to use open source code. Perhaps someday they will break out the components in UI and open source them.
