### ISSUE TITLE
com.mikepenz.materialdrawer.d.ts is not a module

### ISSUE THREAD

**Issue by peer-ligthart** [gethuman/nativescript-sidedrawer#5]
Hi,

When trying to use your plugin in a NativeScript Angular 2 project, I receive an error upon building the application.

Not sure what it means or how to fix it.

> com.mikepenz.materialdrawer.d.ts is not a module

Hopefully someone has a solution to my problem. :)

**Comment by claudiocp** [comment]
Same problem 👍

**Comment by prodigy7** [comment]
You can fix it by solution, suggested here: http://stackoverflow.com/questions/37124267/cannot-use-android-classes-in-nativescript-2

Edit: Sorry, was wrong. Doesn't fix it! :-(

**Comment by prodigy7** [comment]
Looks like used library wasn't supported by the author for nativescript: https://github.com/mikepenz/MaterialDrawer/issues/1770

**Comment by roblav96** [comment]
Most of my plugins are being butchered by diverse typescript `tsconfig.json` files. NativeScript v3 will be addressing these issues so I'll be fixing them then.

**Comment by roblav96** [comment]
@prodigy7 Fixed with https://github.com/gethuman/nativescript-sidedrawer/commit/f2bf34b6b9371933fa5b9cdcf86adec69a52d6c6.
