### ISSUE TITLE
cannot find namespace for android, java, native in com.mikepenz.materialdrawer.d.ts

### ISSUE THREAD

**Issue by gauravbhanderi231** [gethuman/nativescript-sidedrawer#7]
Hi,

When i add this plugin and try to build my project, i get these errors. I am using Angular2 with TS.

**Comment by roblav96** [comment]
@gauravbhanderi231 Newer typescript has made things complicated. I'm gonna be fixing this stuff this week.

**Comment by gauravbhanderi231** [comment]
Perfect, thank you so much.

**Comment by roblav96** [comment]
@gauravbhanderi231 Fixed with https://github.com/gethuman/nativescript-sidedrawer/commit/f2bf34b6b9371933fa5b9cdcf86adec69a52d6c6.
