### ISSUE TITLE
error TS2304: Cannot find name 'java'

### ISSUE THREAD

**Issue by ynwd** [gethuman/nativescript-sidedrawer#8]
Related to #2,  same error on IOS.

> ...
> node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(5,39): error TS2304: Cannot find name 'java'.
> 
> node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(10,39): error TS2503: Cannot find namespace 'android'.
> 
> node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(26,23): error TS2503: Cannot find namespace 'android'.
> 
> node_modules/nativescript-sidedrawer/com.mikepenz.materialdrawer.d.ts(27,38): error TS2503: Cannot find namespace 'android'.
> ...

**Comment by roblav96** [comment]
@yanuwid Fixed with https://github.com/gethuman/nativescript-sidedrawer/commit/f2bf34b6b9371933fa5b9cdcf86adec69a52d6c6
