### ISSUE TITLE
how can i use this plugin with nativescript with vanilla javascript project

### ISSUE THREAD

**Issue by webenformasyon** [gethuman/nativescript-sidedrawer#9]

**Comment by roblav96** [comment]
@webenformasyon exactly how the example shows

**Comment by webenformasyon** [comment]
is this vanilla js ?
import { TnsSideDrawer } from 'nativescript-sidedrawer'

**Comment by Mathijs003** [comment]
How to implement the functions

export function onLoaded(args: EventData) {
	let page: Page = <Page>args.object
	TnsSideDrawer.addGesture(page)
}
export function onUnloaded(args: EventData) {
	let page: Page = <Page>args.object
	TnsSideDrawer.removeGesture(page)
}

in core nativescript ?

I've implemented 

exports.onLoaded = function(args){
    var page = args.object.page;
    sd.TnsSideDrawer.addGesture(page)
}

exports.onUnloaded = function (args) {
    var page = args.object.page
    sd.TnsSideDrawer.removeGesture(page)
} 

But not working so far
